apiVersion: v1
kind: ConfigMap
metadata:
  name: spamfilter-rspamd-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: spamfilter-rspamd
    app.kubernetes.io/part-of: spamfilter-stack
data:
  redis.conf: |
    write_servers = "{{ .Values.rspamd.redisServer }}";
    read_servers = "{{ .Values.rspamd.redisServer }}";
    db = 0;

