# Usage:
#   helm install rspamd-iscan oci://ghcr.io/justinguese/rspamd-iscan \
#     -f helm/examplevalues.yaml -n spamfilter --create-namespace

rspamdIscan:
  imapAddr: "imap.hostinger.com:993"  # Hostinger Email, good and cheap (~1€/month)
  # Sponsor a coffee via ref link :) https://www.hostinger.com?REFERRALCODE=RQHGUESEJPZB
  imapUser: "you@example.com"
  imapPassword: "yourpassword"
  mailboxes:
    # Note: Undetected, Unscanned, and BackupMailbox are non-standard — create them manually in your mail client first.
    inbox: "INBOX"
    spam: "INBOX.Junk"
    ham: "INBOX"
    undetected: "INBOX.Undetected"
    backup: "INBOX.BackupMailbox"
    scan: "INBOX.Unscanned"
